<template>
  <div>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
  </div>
</template>
<script lang="ts">
  export default {
    name: 'Switch',
    setup() {

    }
  }
</script>